name: cep_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.2
  path_provider_android: ^2.0.14
  path_provider_ios: ^2.0.9
  map_launcher: ^2.2.1+1
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  # see https://flutter.dev/custom-fonts/#from-packages
